### ISSUE TITLE
Wrong indication of current position in navigation menu

### ISSUE THREAD

**Issue by Smit2010** [fossasia/pslab-android#1682]
**Actual Behaviour**
When user selects "Share App" from the navigation drawer while in Device, FAQs or About us of the segment represented in drawer, the indication always indicates Instruments irrespective of the current position.

**Expected Behaviour**
Indicator should show the current location in drawer.

**Steps to reproduce it**
Open any of the options in menu (Device, FAQs, About us) then click "Share App" from the drawer >> click cancel and open the drawer and notice the indicator (Highlighted menu) and also the app bar title.

**Screenshots of the issue**
<img src = "https://user-images.githubusercontent.com/34190580/55754444-4d371700-5a6a-11e9-8b58-f92e6ad29a92.gif" width = "300px" />

**Would you like to work on the issue?**
Yes, I would like to work on this issue.

**Comment by neel1998** [comment]
@Smit2010  kindly give comprehensible title to the issue. Current title doesn't quite explain the real issue

**Comment by neel1998** [comment]
@ho-dor  can you check whether this issue occurs after your changes in the PR #1676

**Comment by neel1998** [comment]
@Smit2010 please check once that your repo is updated after the PR #1671  was merged. May be this issue could have been fixed in that PR. If not you can work on it

**Comment by Smit2010** [comment]
@neel1998 After thePR #1671, the issue still persists. So I am continuing working on it.
