### ISSUE TITLE
iOS Deployment Blocked

### ISSUE THREAD

**Issue by AsCress** [fossasia/pslab-android#2810]
We are also blocked on iOS deployment due to some reason that I haven't been able to triage as of yet.
I would take care of this.

**Comment by AsCress** [comment]
CC: @adityastic

**Comment by mariobehling** [comment]
I accepted the new developer terms a few days back. So, it should be working again I think.

**Comment by AsCress** [comment]
@mariobehling Yeah I noticed that. It is still failing due to some other reason. I'm investigating.

**Comment by adityastic** [comment]
<img width="909" height="560" alt="Image" src="https://github.com/user-attachments/assets/cd54825b-fc2a-4f92-bd6e-22fa01b39d99" />

**Comment by adityastic** [comment]
https://github.com/fossasia/pslab-app/issues/2823

**Comment by AsCress** [comment]
Solved in #2825
